### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Haroonabdulrazaq** [Haroonabdulrazaq/My-Cv-HNG-#6]
- [x] In skills section, Language should open up by default
- [x] Add loader and acknowledgment modal to send button
- [x] Add Yandex/Google metrics
- [x] Tinize image
- [x] Check for broken links
